version: "3"
services:
  stock_management:
    container_name: stock
    build: .
    command: nodemon start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3003:3000"
    depends_on:
      - mongo
      - consul
    environment:
      MONGO_URL: mongodb://mongo:27017/stock_management
      AMQP_URL: amqp://guest:guest@host.docker.internal:5672
      NODE_ENV: development
      LOCAL_USER: piloto
      CONSUL_HOST: consul
    networks:
      - restaurant-net

  mongo:
    image: mongo
    ports:
      - "27020:27017"
    networks:
      - restaurant-net

  consul:
    image: consul:1.15
    ports:
      - "8501:8500"
    networks:
      - restaurant-net

networks:
  restaurant-net:
    driver: bridge
