version: "3"
services:
  order_management:
    container_name: order
    build: .
    command: nodemon start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    links:
      - mongo
      - consul
    environment:
      MONGO_URL: mongodb://mongo:27017/order_management
      AMQP_URL: amqp://guest:guest@host.docker.internal:5672
      NODE_ENV: development
      LOCAL_USER: piloto
      CONSUL_HOST: consul
    networks:
      - restaurant-net

  mongo:
    image: mongo
    ports:
      - "27021:27017"
    networks:
      - restaurant-net
  
  consul:
    image: consul:1.15
    ports:
      - "8500:8500"
    networks:
      - restaurant-net

networks:
  restaurant-net:
    driver: bridge
